### ISSUE TITLE
OraLixir warning about not find Priv directory

### ISSUE THREAD

**Issue by cruzfarfan** [c-bik/OraLixir#4] opened 2019-10-20 03:45 UTC
```
$ iex -S mix
Erlang/OTP 22 [erts-10.5.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, pid} = OraLixir.start_link([])
{dpi,load_unsafe,87} priv not found
{dpi,load_unsafe,101} PrivDir "/home/cfarfan/sandbox/elixir/oratest/_build/dev/lib/oranif/priv"
{:ok, #PID<0.212.0>}
```
The directory exist. It is a symlink to /home/cfarfan/sandbox/elixir/oratest/deps/oranif/priv
I was able to use the connection and execute some queries after this warning

**Comment by c-bik** [comment] 2019-10-27 20:46
[lines](https://github.com/c-bik/oranif/blob/37dbb7f96d8c92f944f29b327bcaf213f626f774/src/dpi.erl#L85-L88) to be removed in oranif:
```erlang
            io:format(
                user, "{~p,~p,~p} priv not found~n",
                [?MODULE, ?FUNCTION_NAME, ?LINE]
            ),
```

**Comment by c-bik** [comment] 2019-10-28 07:40
the root of the problem is `code:priv_dir/1` expects an erlang application name (atom) and it was called as `code:priv_dir(?MODULE)` which is `dpi` but the application name is `oranif`

fixed in https://github.com/c-bik/oranif/pull/2

**Closed** 2019-10-30 18:35 UTC
Labels: enhancement
